services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fruit_cbir
      POSTGRES_USER: cbir_user
      POSTGRES_PASSWORD: cbir_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata:
