"""increase dimension of color

Revision ID: 0400874431c7
Revises: bfe1151a9caa
Create Date: 2026-05-04 01:09:30.651225

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = '0400874431c7'
down_revision = 'bfe1151a9caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               existing_nullable=True)

    # ### end Alembic commands ###
