"""add more features

Revision ID: 6c5334ff8c24
Revises: 0400874431c7
Create Date: 2026-05-04 16:57:32.675284

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = '6c5334ff8c24'
down_revision = '0400874431c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gabor', pgvector.sqlalchemy.vector.VECTOR(dim=16), nullable=True))
        batch_op.add_column(sa.Column('hog', pgvector.sqlalchemy.vector.VECTOR(dim=8100), nullable=True))
        batch_op.add_column(sa.Column('convex_hull', pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=True))
        batch_op.add_column(sa.Column('aspect_ratio', pgvector.sqlalchemy.vector.VECTOR(dim=1), nullable=True))
        batch_op.add_column(sa.Column('zernike', pgvector.sqlalchemy.vector.VECTOR(dim=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('zernike')
        batch_op.drop_column('aspect_ratio')
        batch_op.drop_column('convex_hull')
        batch_op.drop_column('hog')
        batch_op.drop_column('gabor')

    # ### end Alembic commands ###
