"""add color_moments and glcm columns

Revision ID: bfe1151a9caa
Revises: c4c97f1fae5b
Create Date: 2026-04-25 14:09:55.001634

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = 'bfe1151a9caa'
down_revision = 'c4c97f1fae5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_moments', pgvector.sqlalchemy.vector.VECTOR(dim=9), nullable=True))
        batch_op.add_column(sa.Column('glcm', pgvector.sqlalchemy.vector.VECTOR(dim=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('glcm')
        batch_op.drop_column('color_moments')

    # ### end Alembic commands ###
