"""initial schema

Revision ID: c4c97f1fae5b
Revises: 
Create Date: 2026-04-25 13:45:44.110500

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = 'c4c97f1fae5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('fruit_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=30), nullable=True),
    sa.Column('filepath', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruits.fruit_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('features',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('color', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('texture', pgvector.sqlalchemy.vector.VECTOR(dim=10), nullable=True),
    sa.Column('shape', pgvector.sqlalchemy.vector.VECTOR(dim=7), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('feature_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('images')
    op.drop_table('fruits')
    # ### end Alembic commands ###
